on:
  push:
    branches: [master]
    tags: ["v*"]
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v6
        with:
          node-version-file: package.json
      - uses: pnpm/action-setup@v4
      - run: pnpm install
      - run: pnpm lint
      - run: pnpm typecheck
      - run: pnpm build
      - run: |
          if ! git diff -q; then
            echo '::error::Generated files are not up-to-date'
            exit 1
          fi
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby-version: ["3.3", "3.4", "4.0"]  # Three latest major versions
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v6
        with:
          node-version-file: package.json
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
      - uses: pnpm/action-setup@v4
      - run: pnpm install
      - run: pnpm test

  publish:
    if: startsWith(github.ref, 'refs/tags/')
    needs: [lint, test]
    runs-on: ubuntu-slim
    permissions:
      contents: write
    steps:
      - uses: actions/github-script@v8
        with:
          script: |
            const ref = (await github.rest.git.getRef({ ...context.repo, ref: context.ref })).data;
            if (ref.object.type !== "tag") throw new Error("ref is not an annotated tag");
            const tag = (await github.rest.git.getTag({ ...context.repo, tag_sha: ref.object.sha })).data;
            if (!tag.verification?.verified) throw new Error(`tag is not verified: ${tag.verification?.reason}`);
            await github.rest.repos.createRelease({
              ...context.repo,
              tag_name: tag.tag,
              name: tag.tag,
              prerelease: !!tag.tag.match(/[a-z]/i),
              draft: false,
            });
            await github.rest.git.updateRef({
              ...context.repo,
              ref: ref.ref.split('.')[0],
              sha: tag.sha,
            });
